spring:
  application:
    name: userService

  datasource:
    url: jdbc:postgresql://localhost:5432/linkedinUserDB
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9020

