spring:
  application:
    name: userService

  datasource:
    url: jdbc:postgresql://localhost:5432/linkedinUserDB
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9020
  servlet:
    context-path: /api/v1/users

jwt:
  secret: dgsdgsd3434dg346534gergt55646t54egdgsthdthrhdthgsdrhrtyrey34564643reg